name: Docker Image CI

on:
  push:
    branch: ["main"]

jobs:
  build-test:
  #  defenition plateform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          npm run test
        working-directory: ./node-app