name: Publish Docker Image

on:
  push:

jobs:
  build-test:
  #  defenition plateform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
  # instructions
      - run: npm ci
      - run: npm run build
      - run: npm test
  
  deploy:
    runs-on: ubuntu-latest
# le job précédent doit etre réussi pour lancer celui la
    needs: build-test

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
        # nom de 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -  name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/joke-app:latest